### PR TITLE
Removes two 3rd party links in menu

### PR DESCRIPTION
**Pull request by spirillen**
See https://github.com/easylist/easylist/pull/9874#issuecomment-980780453 for details

### CODE REVIEW

**Comment by Yuki2718** [comment]
I think it's better to open a new PR with a new branch in EL repo.

**Comment by Yuki2718** [comment]
Follow-up PR is not rare, smed79 often does this.

**Comment by spirillen** [comment]
It was mostly to keep things together rather than having them spread around...

**Comment by Yuki2718** [comment]
In my past PR EL maintainer didn't like my filters for similar staff so I won't add them in the same branch. There are too many ways to write filters for href.

**Comment by spirillen** [comment]
There is, and I agree with you, it can difficult to make the rule so they are matching there daily mode :shrug:

**Pull request closed without merging**
